# Custom Language File for Launcher Customizer

[ejs.app]
title = "KGInfoServs Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur KGInfoServs"
welcomeDescription = "Découvrez une nouvelle façon de jouer, profiter plainement du jeux avec vos amis, divers type de jeux sont proposé avec des fonctions unique !"
welcomeDescCTA = "A vous de les découvrir"
