# Custom Language File for Launcher Customizer

[ejs.app]
title = "KGInfoServs Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Bossbirdyman51/KGInfoServsLauncherV4"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/UxxdkDy"

[ejs.settings]
sourceGithubLink = "https://github.com/Bossbirdyman51/KGInfoServsLauncherV4"
supportLink = "https://github.com/Bossbirdyman51/KGInfoServsLauncherV4/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur KGInfoServs"
welcomeDescription = "Découvrez une nouvelle façon de jouer, profiter plainement du jeux avec vos amis, divers type de jeux sont proposé avec des fonctions unique !"
welcomeDescCTA = "A vous de les découvrir"
